import type { Metadata } from "next";
import ThemeRegistry from "@/components/theme/ThemeRegistry";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry initialMode="light" options={{ key: "mui" }}>
        {children}
      </ThemeRegistry>
    </html>
  );
}
